[package]
name = "fuel-crypto-shader"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
fuel-crypto-shared = { path = "../shared" }
spirv-std = { workspace = true }
